### ISSUE TITLE
NPEs are thrown randomly.

### ISSUE THREAD

**Issue by ScrapCodes** [aarondav/scala-imports-organizer#4]
It is not clear yet, how to reproduce this.

`Error during dispatching of java.awt.event.KeyEvent[KEY_PRESSED,keyCode=79,keyText=O,keyChar='',modifiers=Ctrl+Shift,extModifiers=Ctrl+Shift,keyLocation=KEY_LOCATION_STANDARD,rawCode=32,primaryLevelUnicode=111,scancode=0,extendedKeyCode=0x4f] on frame0
java.lang.NullPointerException
    at com.scalaImportsOrganizer.ScalaImportsOrganizerAction$ScalaImportsOrganizer.removePriorImports(ScalaImportsOrganizerAction.scala:130)
    at com.scalaImportsOrganizer.ScalaImportsOrganizerAction$ScalaImportsOrganizer.organizeImports(ScalaImportsOrganizerAction.scala:66)
    at com.scalaImportsOrganizer.ScalaImportsOrganizerAction$$anonfun$actionPerformed$1.apply$mcV$sp(ScalaImportsOrganizerAction.scala:277)
    at com.scalaImportsOrganizer.ScalaImportsOrganizerAction$$anon$1.run(ScalaImportsOrganizerAction.scala:306)
    at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:124)
    at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:99)
    at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:85)
    at com.scalaImportsOrganizer.ScalaImportsOrganizerAction$$anon$2.run(ScalaImportsOrganizerAction.scala:309)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1013)
    at com.scalaImportsOrganizer.ScalaImportsOrganizerAction.withinWritableContext(ScalaImportsOrganizerAction.scala:311)
    at com.scalaImportsOrganizer.ScalaImportsOrganizerAction.actionPerformed(ScalaImportsOrganizerAction.scala:274)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:564)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:611)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:463)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:206)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:494)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:348)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)`

**Comment by aarondav** [comment]
Fixed in 0.1.3.
